name: row_collection
description: Collection of various custom widgets, useful for displaying information in Columns.
version: 0.2.4
homepage: https://github.com/jesusrp98/row_collection

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  row_item: ^2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
