name: row_collection
description: Collection of various custom widgets, useful in Columns.
version: 0.0.1
author: Jesus Rodriguez <jesusrope98@outlook.com>
homepage: https://github.com/jesusrp98/row_collection

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter